### ISSUE TITLE
some problem with filescanner subfolder

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#156]
everytime i want to scan a subfolder from my movie root i get this warning 

Dec 17, 2014 8:14:23 AM name.pachler.nio.file.ext.Bootstrapper newWatchService
WARNING: null
java.lang.UnsatisfiedLinkError: no jpathwatch-native in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1119)
        at name.pachler.nio.file.impl.NativeLibLoader.loadDefaultLibrary(NativeLibLoader.java:84)
        at name.pachler.nio.file.impl.NativeLibLoader.loadLibrary(NativeLibLoader.java:245)
        at name.pachler.nio.file.impl.LinuxPathWatchService.<clinit>(LinuxPathWatchService.java:105)
        at name.pachler.nio.file.ext.Bootstrapper.newWatchService(Bootstrapper.java:80)
        at name.pachler.nio.file.FileSystems$1.newWatchService(FileSystems.java:40)
        at org.yamj.filescanner.tools.Watcher.<init>(Watcher.java:36)
        at org.yamj.filescanner.ScannerManagementImpl.runScanner(ScannerManagementImpl.java:238)
        at org.yamj.filescanner.FileScanner.execute(FileScanner.java:108)
        at org.yamj.filescanner.FileScanner.main(FileScanner.java:73)

**Comment by modmax** [comment]
The problem is that watch service could be enabled by filescanner properties.

If watching is not possible on the target system (cause native support is missing) and watching should be enabled, than a warning will be displayed and the watch service will not start
