### ISSUE TITLE
unexpected 503 - to be treated 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#159]
could you treat ERROR 503 rather than letting fail with java ERROR

[07:55:03] ERROR org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper  - Failed retrieving Allocine filmography for person: 690691
[07:55:03] ERROR org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper  - Allocine error
java.lang.RuntimeException: Unexpected status 503 for uri http://api.allocine.fr/rest/v3/filmography?partner=100043982026&profile=large&format=json&code=690691&striptags=synopsis%2Csynopsisshort&sed=20141222&sig=TOW7d4W1oF%2FZiFBXKonhj5C%2FdVA%3D
	at org.yamj.core.tools.web.PoolingHttpClient.requestContent(PoolingHttpClient.java:116)
	at com.moviejukebox.allocine.AllocineApi.readJsonObject(AllocineApi.java:152)
	at com.moviejukebox.allocine.AllocineApi.getPersonFilmography(AllocineApi.java:300)
	at org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper.getFilmographyInfos(AllocineApiWrapper.java:270)
	at org.yamj.core.service.metadata.online.allocine.AllocineScanner.scanFilmography(AllocineScanner.java:633)
	at org.yamj.core.service.metadata.online.OnlineScannerService.scanFilmography(OnlineScannerService.java:330)
	at org.yamj.core.service.metadata.MetadataScannerService.scanFilmography(MetadataScannerService.java:167)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[07:55:03] ERROR org.yamj.core.service.metadata.online.allocine.AllocineScanner  - Can't find filmography for person 'Caroline Bonin' with id 690691

**Comment by modmax** [comment]
The error code 503 means, that the service is temporary not availabe and the allocine api returns an invalid object to the yamj3 core.

In normal cases this leads to an error and the filmography scan will be marked as error.

BUT:
There are some configuration parameters to tweak this error handling.
In case of allocine filmography scan this is "allocine.maxRetries.filmography"
By default this is 0, which means: error occurs, so set status to ERROR.

In set to another value (like 3 or 5), then 3 or 5 retries will be done, until the filmography scan is marked as errornessin the database.

Right now there are several maxRetries settings for different purposes:
See following config entries:

select * from configuration c where c.config_key like '%maxRetries%';

So there is nothing to do right now for this issue.

**Comment by jluc2808** [comment]
ok for the explanation , but coould trap the error and just display ERROR in the log rather than letting java make a javaException  which will confuse and let people think it's a as a program problem

**Comment by jluc2808** [comment]
error 503 is now trapped tested ok
