### ISSUE TITLE
trap and treat  error 500 , 503, storage error 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#160]
some known ERROR should be trapped and treated , rather than letting java failed with all the consequences (error line xx, ...) 
here a short list of what is known : 

ERROR 500
[06:04:43] ERROR org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper  - Failed retrieving Allocine infos for movie: 128357
[06:04:43] ERROR org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper  - Allocine error
java.lang.RuntimeException: Unexpected status 500 for uri http://api.allocine.fr/rest/v3/movie?partner=100043982026&code=128357&profile=large&filter=movie&format=json&striptags=synopsis%2Csynopsisshort&sed=20150109&sig=vMGYPpvpnKpzutfnCSY9fMEqRSo%3D
	at org.yamj.core.tools.web.PoolingHttpClient.requestContent(PoolingHttpClient.java:116)
......
[06:04:43] ERROR org.yamj.core.service.metadata.online.allocine.AllocineScanner  - Can't find informations for movie with id 128357

ERROR 503
[06:12:05] ERROR org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper  - Failed retrieving Allocine filmography for person: 432835
[06:12:05] ERROR org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper  - Allocine error
java.lang.RuntimeException: Unexpected status 503 for uri http://api.allocine.fr/rest/v3/filmography?partner=100043982026&profile=large&format=json&code=432835&striptags=synopsis%2Csynopsisshort&sed=20150109&sig=ytTnI2QweFP4AJ07TTSJ8VlNPbQ%3D
	at org.yamj.core.tools.web.PoolingHttpClient.requestContent(PoolingHttpClient.java:116)
.......
[06:12:05] ERROR org.yamj.core.service.metadata.online.allocine.AllocineScanner  - Can't find filmography for person 'Fred Luck' with id 432835

ERROR storage error 
[06:12:08] ERROR org.yamj.core.service.metadata.MetadataScannerService  - Failed storing person filmography 9289-'Denys Darahan'
[06:12:08] ERROR org.yamj.core.service.metadata.MetadataScannerService  - Storage error
org.springframework.dao.DataIntegrityViolationException: not-null property references a null or transient value: org.yamj.core.database.model.FilmParticipation.jobType; nested exception is org.hibernate.PropertyValueException: not-null property references a null or transient value: org.yamj.core.database.model.FilmParticipation.jobType
	at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:160)
.....
Caused by: org.hibernate.PropertyValueException: not-null property references a null or transient value: org.yamj.core.database.model.FilmParticipation.jobType

**Comment by modmax** [comment]
Closed with 34ebabab19322cb05391a088604989e1e1fa6f85

**Comment by modmax** [comment]
Refs #164
