### ISSUE TITLE
ERROR with filmography

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#164]
i have a lot of ERROR with filmography (on windows and on the NAS) 

[07:49:22] INFO  org.yamj.core.service.metadata.online.OnlineScannerService  - Scanning for filmography of person 16176-'Charles Papasoff' using allocine
[07:49:22] DEBUG org.yamj.core.tools.web.PoolingHttpClient  - Stale connection check
[07:49:22] DEBUG org.yamj.core.tools.web.PoolingHttpClient  - Attempt 1 to execute request
[07:49:22] DEBUG org.yamj.core.tools.web.PoolingHttpClient  - Connection can be kept alive indefinitely
[07:49:22] DEBUG org.yamj.core.service.metadata.online.OnlineScannerService  - Person filmography 16176-'Charles Papasoff', scanned OK
[07:49:22] ERROR org.yamj.core.service.metadata.MetadataScannerService  - Failed storing person filmography 16176-'Charles Papasoff'
[07:49:22] ERROR org.yamj.core.service.metadata.MetadataScannerService  - Storage error
org.springframework.dao.DataIntegrityViolationException: not-null property references a null or transient value: org.yamj.core.database.model.FilmParticipation.jobType; nested exception is org.hibernate.PropertyValueException: not-null property references a null or transient value: org.yamj.core.database.model.FilmParticipation.jobType
	at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:160)
	at org.springframework.orm.hibernate4.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:682)
	at org.springframework.orm.hibernate4.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:564)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:755)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:475)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:270)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)
	at org.yamj.core.database.service.MetadataStorageService$$EnhancerBySpringCGLIB$$92e59bc9.updateScannedPersonFilmography(<generated>)
	at org.yamj.core.service.metadata.MetadataScannerService.scanFilmography(MetadataScannerService.java:193)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
Caused by: org.hibernate.PropertyValueException: not-null property references a null or transient value: org.yamj.core.database.model.FilmParticipation.jobType
	at org.hibernate.engine.internal.Nullability.checkNullability(Nullability.java:103)
	at org.hibernate.action.internal.AbstractEntityInsertAction.nullifyTransientReferencesIfNotAlready(AbstractEntityInsertAction.java:132)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:69)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:395)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:229)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:209)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:193)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:321)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:286)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:192)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:206)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:191)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:114)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90)
	at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:654)
	at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:646)
	at org.hibernate.engine.spi.CascadingAction$5.cascade(CascadingAction.java:258)
	at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:396)
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:339)
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:207)
	at org.hibernate.engine.internal.Cascade.cascadeCollectionElements(Cascade.java:426)
	at org.hibernate.engine.internal.Cascade.cascadeCollection(Cascade.java:366)
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:342)
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:207)
	at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:164)
	at org.hibernate.event.internal.AbstractFlushingEventListener.cascadeOnFlush(AbstractFlushingEventListener.java:165)
	at org.hibernate.event.internal.AbstractFlushingEventListener.prepareEntityFlushes(AbstractFlushingEventListener.java:156)
	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:89)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:55)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1159)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:404)
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)
	at org.springframework.orm.hibernate4.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:556)
	... 13 more
[07:49:25] DEBUG org.yamj.core.service.ScanningScheduler  - Finished filmography data scanning

**Comment by jluc2808** [comment]
the error is still there every 10 minutes  if some value is missing for the database, as we known it's mandatory,  could you set a value like unknown or invalid or something else to avoid the problem

[03:26:16] ERROR org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper  - Failed retrieving Allocine filmography for person: 20190
[03:26:16] ERROR org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper  - Allocine error
com.moviejukebox.allocine.AllocineException
	at com.moviejukebox.allocine.AllocineApi.requestWebPage(AllocineApi.java:385)
	at com.moviejukebox.allocine.AllocineApi.readJsonObject(AllocineApi.java:132)
	at com.moviejukebox.allocine.AllocineApi.getPersonFilmography(AllocineApi.java:338)
	at org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper.getFilmographyInfos(AllocineApiWrapper.java:270)
	at org.yamj.core.service.metadata.online.allocine.AllocineScanner.scanFilmography(AllocineScanner.java:633)
	at org.yamj.core.service.metadata.online.OnlineScannerService.scanFilmography(OnlineScannerService.java:330)
	at org.yamj.core.service.metadata.MetadataScannerService.scanFilmography(MetadataScannerService.java:189)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
[03:26:16] ERROR org.yamj.core.service.metadata.online.allocine.AllocineScanner  - Can't find filmography for person 'Chazz Palminteri' with id 20190

**Comment by jluc2808** [comment]
tested with last release , seems ok

**Comment by jluc2808** [comment]
i found some java scanning error with java error 

[06:32:13] ERROR org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper  - Failed to search for person infos: Patricia Kerrigan DiCerto
com.moviejukebox.allocine.AllocineException
	at com.moviejukebox.allocine.AllocineApi.requestWebPage(AllocineApi.java:385)
	at com.moviejukebox.allocine.AllocineApi.readJsonObject(AllocineApi.java:132)
	at com.moviejukebox.allocine.AllocineApi.searchPersons(AllocineApi.java:209)
	at org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper.getAllocinePersonId(AllocineApiWrapper.java:166)
	at org.yamj.core.service.metadata.online.allocine.AllocineScanner.getPersonId(AllocineScanner.java:312)
	at org.yamj.core.service.metadata.online.allocine.AllocineScanner.getPersonId(AllocineScanner.java:303)
	at org.yamj.core.service.metadata.online.allocine.AllocineScanner.scanFilmography(AllocineScanner.java:632)
	at org.yamj.core.service.metadata.online.OnlineScannerService.scanFilmography(OnlineScannerService.java:330)
	at org.yamj.core.service.metadata.MetadataScannerService.scanFilmography(MetadataScannerService.java:189)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[06:32:16] WARN  org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper  - Allocine request failed with status 503 for person filmography: 680334
[06:32:17] WARN  org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper  - Allocine request failed with status 503 for person filmography: 463611
[06:32:18] ERROR org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper  - Failed to search for person infos: Todd Cherniawsky
com.moviejukebox.allocine.AllocineException
	at com.moviejukebox.allocine.AllocineApi.requestWebPage(AllocineApi.java:385)
	at com.moviejukebox.allocine.AllocineApi.readJsonObject(AllocineApi.java:132)
	at com.moviejukebox.allocine.AllocineApi.searchPersons(AllocineApi.java:209)
	at org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper.getAllocinePersonId(AllocineApiWrapper.java:166)
	at org.yamj.core.service.metadata.online.allocine.AllocineScanner.getPersonId(AllocineScanner.java:312)
	at org.yamj.core.service.metadata.online.allocine.AllocineScanner.getPersonId(AllocineScanner.java:303)
	at org.yamj.core.service.metadata.online.allocine.AllocineScanner.scanFilmography(AllocineScanner.java:632)
	at org.yamj.core.service.metadata.online.OnlineScannerService.scanFilmography(OnlineScannerService.java:330)
	at org.yamj.core.service.metadata.MetadataScannerService.scanFilmography(MetadataScannerService.java:189)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[06:32:19] WARN  org.yamj.core.service.metadata.online.OnlineScannerService  - Person filmography 1423-'Todd Cherniawsky', not found
[06:32:20] ERROR org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper  - Failed to search for person infos: Kevin Phipps
com.moviejukebox.allocine.AllocineException
	at com.moviejukebox.allocine.AllocineApi.requestWebPage(AllocineApi.java:385)
	at com.moviejukebox.allocine.AllocineApi.readJsonObject(AllocineApi.java:132)
	at com.moviejukebox.allocine.AllocineApi.searchPersons(AllocineApi.java:209)
	at org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper.getAllocinePersonId(AllocineApiWrapper.java:166)
	at org.yamj.core.service.metadata.online.allocine.AllocineScanner.getPersonId(AllocineScanner.java:312)
	at org.yamj.core.service.metadata.online.allocine.AllocineScanner.getPersonId(AllocineScanner.java:303)
	at org.yamj.core.service.metadata.online.allocine.AllocineScanner.scanFilmography(AllocineScanner.java:632)
	at org.yamj.core.service.metadata.online.OnlineScannerService.scanFilmography(OnlineScannerService.java:330)
	at org.yamj.core.service.metadata.MetadataScannerService.scanFilmography(MetadataScannerService.java:189)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[06:32:22] WARN  org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper  - Allocine request failed with status 503 for person filmography: 76194

**Comment by modmax** [comment]
This isse has been closed with commit 1ea3157ea0e670bb900058b09d5b155df71034aa

**Comment by jluc2808** [comment]
sorry @modmax  but i find another one (after updating the release
20:45:51] ERROR org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper  - Failed retrieving Allocine filmography for person: 139133
[20:45:51] WARN  org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper  - Allocine error
com.moviejukebox.allocine.AllocineException: java.net.SocketTimeoutException: Read timed out
	at com.moviejukebox.allocine.AllocineApi.requestWebPage(AllocineApi.java:394)
	at com.moviejukebox.allocine.AllocineApi.readJsonObject(AllocineApi.java:132)
	at com.moviejukebox.allocine.AllocineApi.getPersonFilmography(AllocineApi.java:338)
	at org.yamj.core.service.metadata.online.allocine.AllocineApiWrapper.getFilmographyInfos(AllocineApiWrapper.java:298)
	at org.yamj.core.service.metadata.online.allocine.AllocineScanner.scanFilmography(AllocineScanner.java:652)
	at org.yamj.core.service.metadata.online.OnlineScannerService.scanFilmography(OnlineScannerService.java:330)
	at org.yamj.core.service.metadata.MetadataScannerService.scanFilmography(MetadataScannerService.java:189)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:197)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.yamj.api.common.http.DefaultPoolingHttpClient.requestContent(DefaultPoolingHttpClient.java:115)
	at org.yamj.core.tools.web.PoolingHttpClient.requestContent(PoolingHttpClient.java:108)
	at com.moviejukebox.allocine.AllocineApi.requestWebPage(AllocineApi.java:382)
	... 10 more
[20:45:51] ERROR org.yamj.core.service.metadata.online.allocine.AllocineScanner  - Can't find filmography for person 'John Stevenson'

**Comment by modmax** [comment]
SocketTimeoutException will also be handled as 503 error

**Comment by jluc2808** [comment]
tested no more errors  - OK
