### ISSUE TITLE
Failed parsing NFO: Invalid byte 1 of 1-byte UTF-8 sequence.

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#165]
i'm using telnet under windows for the NAS , and test the same sequence directly with jetty under windows 

the more strange is that NFO stagefile have the status DONE not INVALID   ???
(i will send you the nfo, so you could reproduce with the same one)  

i have the same error :  look at the 2 logs 

log with jetty on the NAS with telnet session
[02:06:26] ERROR org.yamj.core.service.metadata.nfo.InfoReader  - Failed parsing NFO file: Arthur et La vengeance de Maltazard (2009) - 1080p [SET Arthur et les Minimoys-2].nfo
com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:691)
	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:557)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1762)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(XMLEntityScanner.java:1435)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2807)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at org.yamj.core.tools.xml.DOMHelper.getDocFromFile(DOMHelper.java:193)
	at org.yamj.core.service.metadata.nfo.InfoReader.readXmlNfo(InfoReader.java:197)
	at org.yamj.core.service.metadata.nfo.InfoReader.readNfoFile(InfoReader.java:118)
	at org.yamj.core.service.metadata.nfo.NfoScannerService.scanNFOs(NfoScannerService.java:315)
	at org.yamj.core.service.metadata.nfo.NfoScannerService.scanMovie(NfoScannerService.java:72)
	at org.yamj.core.service.metadata.MetadataScannerService.scanMovie(MetadataScannerService.java:69)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)

log wit jetty on windows 
[08:23:07] ERROR org.yamj.core.service.metadata.nfo.InfoReader  - Failed parsing NFO file: Arthur et La vengeance de Maltazard (2009) - 1080p [SET Arthur et les Minimoys-2].nfo
com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Octet 1 de la séquence UTF-8 à 1 octets non valide.
	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at org.yamj.core.tools.xml.DOMHelper.getDocFromFile(DOMHelper.java:193)
	at org.yamj.core.service.metadata.nfo.InfoReader.readXmlNfo(InfoReader.java:197)
	at org.yamj.core.service.metadata.nfo.InfoReader.readNfoFile(InfoReader.java:118)
	at org.yamj.core.service.metadata.nfo.NfoScannerService.scanNFOs(NfoScannerService.java:315)
	at org.yamj.core.service.metadata.nfo.NfoScannerService.scanMovie(NfoScannerService.java:72)
	at org.yamj.core.service.metadata.MetadataScannerService.scanMovie(MetadataScannerService.java:69)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by jluc2808** [comment]
adding this sequence at the beginning of the nfo 
< ?xml version="1.0" encoding="ISO-8859-1"?>
no error returned   ==> OK

if i set 
< ?xml version="1.0" encoding="UFT-8"?> or < ?xml version="1.0" encoding="UFT8"?>
i get an error 
java.io.UnsupportedEncodingException: UFT-8j or ava.io.UnsupportedEncodingException: UFT8

if i set < ?xml version="1.0" encoding="ISO-8859-15"?>
no error  ==> ok

**Comment by modmax** [comment]
UFT-8 i no valid character encoding, cause it's misspelled.

Correct encoding is: UTF-8

Also the file itself may have a character encoding.
I.e: When you open a text file under windows with notpad then you can choose
the encoding which should be use for that text file.
That also can be an issue ...
