### ISSUE TITLE
NULL pointer exception with "api/video/seriesinfo" having artwork dataitem

### ISSUE THREAD

**Issue by Diodato** [YAMJ/yamj-v3#173]
"api/video/seriesinfo?id=1" works OK
"api/video/seriesinfo?id=1&dataitems=artwork" causes NULL pointer exception

----------------------------------------
java.lang.NullPointerException
	at org.yamj.core.database.dao.ApiDao.getSeriesInfo(ApiDao.java:2235)
	at org.yamj.core.database.service.JsonApiStorageService.getSeriesInfo(JsonApiStorageService.java:194)
	at org.yamj.core.database.service.JsonApiStorageService$$FastClassBySpringCGLIB$$145385d0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at org.yamj.core.database.service.JsonApiStorageService$$EnhancerBySpringCGLIB$$aadc0ce4.getSeriesInfo(<generated>)
	at org.yamj.core.api.json.VideoController.getSeriesInfo(VideoController.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
.....

**Comment by Diodato** [comment]
forgot about labels
