### ISSUE TITLE
unable to start jetty with last updated at 2015/04/17 14:15:49

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#190]
when i start jetty.cmd 

Exception in thread "main" java.lang.IllegalArgumentException: Invalid format: "Yet Another Movie Jukebox"
        at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:899)
        at org.yamj.common.tools.DateTimeTools.parseDate(DateTimeTools.java:247)
        at org.yamj.common.model.YamjInfo.<init>(YamjInfo.java:86)
        at org.yamj.jetty.Start.main(Start.java:67)
Appuyez sur une touche pour continuer...

**Comment by Omertron** [comment]
Yeah, working on the fix

**Comment by jluc2808** [comment]
tested ok
