### ISSUE TITLE
error scanning un voisin trop parfait 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#191]
with and without NFO i get the same error with this movie 
Un voisin trop parfait (2015) - 1080p.BluRay.x264.mkv

[23:30:34] DEBUG org.yamj.core.tools.LanguageTools  - Scanning media file T:\video\Film\Un voisin trop parfait (2015) - 1080p.BluRay.x264.mkv
[23:30:39] DEBUG org.yamj.core.service.ScanningScheduler  - Finished media file scanning
[23:30:39] INFO  org.yamj.core.service.ScanningScheduler  - Found 1 metadata objects to process; scan with 1 threads
[23:30:39] INFO  org.yamj.core.service.metadata.nfo.NfoScannerService  - Scanning NFO data for movie 'Un voisin trop parfait_2015'
[23:30:39] DEBUG org.yamj.core.service.metadata.nfo.NfoScannerService  - Scan NFO file 1162-'Un voisin trop parfait (2015) - 1080p.BluRay.x264.nfo'
[23:30:39] DEBUG org.yamj.core.service.metadata.nfo.InfoReader  - Found allocine ID: 223822
[23:30:39] DEBUG org.yamj.core.service.metadata.nfo.InfoReader  - Found tmdb ID: 241251
[23:30:39] DEBUG org.yamj.core.service.metadata.nfo.InfoReader  - Successfully scanned Un voisin trop parfait (2015) - 1080p.BluRay.x264.nfo as XML format
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - COUNTRIES (VideoData) priorities [api, nfo, allocine, tmdb, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - COUNTRIES (Series) priorities [api, nfo, allocine, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - GENRES (VideoData) priorities [api, nfo, allocine, tmdb, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - GENRES (Series) priorities [api, nfo, allocine, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - STUDIOS (VideoData) priorities [api, nfo, allocine, tmdb, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - STUDIOS (Series) priorities [api, nfo, allocine, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - ORIGINALTITLE (VideoData) priorities [api, nfo, allocine, tmdb, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - ORIGINALTITLE (Series) priorities [api, nfo, allocine, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - ORIGINALTITLE (Season) priorities [api, nfo, allocine, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - OUTLINE (VideoData) priorities [api, nfo, allocine, tmdb, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - OUTLINE (Series) priorities [api, nfo, allocine, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - OUTLINE (Season) priorities [api, nfo, allocine, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - PLOT (VideoData) priorities [api, nfo, allocine, tmdb, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - PLOT (Series) priorities [api, nfo, allocine, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - PLOT (Season) priorities [api, nfo, allocine, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - QUOTE (VideoData) priorities [api, nfo, allocine, tmdb, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - RELEASEDATE (VideoData) priorities [api, nfo, allocine, tmdb, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - TAGLINE (VideoData) priorities [api, nfo, allocine, tmdb, tvdb]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - TITLE (VideoData) priorities [api, nfo, allocine, tmdb, tvdb, filename]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - TITLE (Series) priorities [api, nfo, allocine, tvdbfilename]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - TITLE (Season) priorities [api, nfo, allocine, tvdbfilename]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - YEAR (VideoData) priorities [api, nfo, allocine, tmdb, tvdbfilename]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - YEAR (Series) priorities [api, nfo, allocine, tvdbfilename]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - YEAR (Season) priorities [api, nfo, allocine, tvdbfilename]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - NAME (Person) priorities [api, nfo, tmdb, allocine]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - FIRSTNAME (Person) priorities [api, nfo, tmdb, allocine]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - LASTNAME (Person) priorities [api, nfo, tmdb, allocine]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - BIRTHDAY (Person) priorities [api, nfo, tmdb, allocine]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - BIRTHPLACE (Person) priorities [api, nfo, tmdb, allocine]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - BIRTHNAME (Person) priorities [api, nfo, tmdb, allocine]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - DEATHDAY (Person) priorities [api, nfo, tmdb, allocine]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - DEATHDAY (Person) priorities [api, nfo, tmdb, allocine]
[23:30:39] DEBUG org.yamj.core.tools.OverrideTools  - BIOGRAPHY (Person) priorities [api, nfo, tmdb, allocine]
[23:30:39] DEBUG org.yamj.core.service.metadata.nfo.NfoScannerService  - Scanned NFO data for movie 'Un voisin trop parfait_2015'
[23:30:39] INFO  org.yamj.core.service.metadata.online.OnlineScannerService  - Scanning movie data for 'Un voisin trop parfait' using allocine
[23:30:39] DEBUG org.yamj.core.tools.web.PoolingHttpClient  - IO download host: http://api.allocine.fr; rule: .*, maxRequests: 2
[23:30:39] ERROR org.yamj.core.service.metadata.online.OnlineScannerService  - Failed scanning movie with allocine scanner
[23:30:39] WARN  org.yamj.core.service.metadata.online.OnlineScannerService  - Scanning error
java.lang.NullPointerException
	at com.moviejukebox.allocine.model.AbstractBaseInfos.getUserRating(AbstractBaseInfos.java:67)
	at com.moviejukebox.allocine.model.MovieInfos.getUserRating(MovieInfos.java:106)
	at org.yamj.core.service.metadata.online.AllocineScanner.scan(AllocineScanner.java:201)
	at org.yamj.core.service.metadata.online.OnlineScannerService.scanMovie(OnlineScannerService.java:115)
	at org.yamj.core.service.metadata.MetadataScannerService.scanMovie(MetadataScannerService.java:72)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[23:30:39] DEBUG org.yamj.core.service.metadata.online.OnlineScannerService  - Alternate scanning movie data for 'Un voisin trop parfait' using tmdb
[23:30:39] INFO  org.apache.http.impl.execchain.RetryExec  - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://api.themoviedb.org:80: The target server failed to respond
[23:30:39] INFO  org.apache.http.impl.execchain.RetryExec  - Retrying request to {}->http://api.themoviedb.org:80
[23:30:41] DEBUG org.yamj.core.service.metadata.MetadataScannerService  - Updated movie in database: 544-'Un voisin trop parfait'
[23:30:44] DEBUG org.yamj.core.service.ScanningScheduler  - Finished metadata scanning

**Comment by jluc2808** [comment]
no more error with revision 9d9857b

**Comment by modmax** [comment]
Bug fixed in allocine API if userRating or pressRating wasn't present.
In that case no rating will be set.

**Comment by jluc2808** [comment]
@modmax ????

**Comment by Omertron** [comment]
He means that the allocine API did not pass a rating back to YAMJ and that was what was causing the issue. He's fixed it in allocine and therefore it will fix it in YAMJ

**Comment by modmax** [comment]
Stuart has described it excellently ... :-)

**Comment by jluc2808** [comment]
@modmax ????

**Comment by Omertron** [comment]
It was made on the allocine project, which is a dependency of this project.

Jenkins will compile the Allocine plugin and then *should* kick off a build of YAMJ3 to update the plugin
