### ISSUE TITLE
jetty is cycling with error with tmdb filmography updated

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#207]
with 0142d52
update filmography with tmdb give an error with jetty cycling on this error : 
[23:21:28] ERROR org.yamj.core.service.metadata.MetadataScannerService  - Failed storing person filmography 1-'Guillermo del Toro'
[23:21:28] ERROR org.yamj.core.service.metadata.MetadataScannerService  - Storage error
java.lang.NullPointerException
	at org.yamj.core.database.model.FilmParticipation.setRole(FilmParticipation.java:143)
	at org.yamj.core.database.model.FilmParticipation.merge(FilmParticipation.java:212)
	at org.yamj.core.database.service.MetadataStorageService.updateScannedPersonFilmography(MetadataStorageService.java:359)
	at org.yamj.core.database.service.MetadataStorageService$$FastClassBySpringCGLIB$$743c57e5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at org.yamj.core.database.service.MetadataStorageService$$EnhancerBySpringCGLIB$$eef2f53b.updateScannedPersonFilmography(<generated>)
	at org.yamj.core.service.metadata.MetadataScannerService.scanFilmography(MetadataScannerService.java:193)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by modmax** [comment]
Problem is that line in "FilmParticipant.java";

this.role = role.substring(0, Math.min(role.length(), 254));

Reason: role is nullable value and not all movie database have the role stored; so there must just be a change to:

this.role = (role == null ? null : role.substring(0, Math.min(role.length(), 254)));

**Comment by jluc2808** [comment]
i think it's not already completly solved
i get this error for each person : 
[16:01:08] ERROR org.yamj.core.service.metadata.online.OnlineScannerService  - Failed scanning person (ID '17048') data with scanner tmdb 
[16:01:08] WARN  org.yamj.core.service.metadata.online.OnlineScannerService  - Scanning error
java.lang.NullPointerException
	at com.omertron.themoviedbapi.methods.TmdbPeople.getPersonInfo(TmdbPeople.java:83)
	at com.omertron.themoviedbapi.TheMovieDbApi.getPersonInfo(TheMovieDbApi.java:1157)
	at org.yamj.core.service.metadata.online.TheMovieDbApiWrapper.getPersonInfo(TheMovieDbApiWrapper.java:140)
	at org.yamj.core.service.metadata.online.TheMovieDbScanner.scan(TheMovieDbScanner.java:280)
	at org.yamj.core.service.metadata.online.OnlineScannerService.scanPerson(OnlineScannerService.java:250)
	at org.yamj.core.service.metadata.MetadataScannerService.scanPerson(MetadataScannerService.java:158)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by modmax** [comment]
Same as issue #214
