### ISSUE TITLE
failed storing person Filmography

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#211]
jetty loop on error : 
[19:57:19] ERROR org.yamj.core.service.metadata.MetadataScannerService  - Failed storing person filmography 5537-'Michael Rose'
[19:57:19] ERROR org.yamj.core.service.metadata.MetadataScannerService  - Storage error
java.lang.NullPointerException
	at org.yamj.core.database.model.FilmParticipation.setRole(FilmParticipation.java:143)
	at org.yamj.core.database.model.FilmParticipation.merge(FilmParticipation.java:212)
	at org.yamj.core.database.service.MetadataStorageService.updateScannedPersonFilmography(MetadataStorageService.java:359)
	at org.yamj.core.database.service.MetadataStorageService$$FastClassBySpringCGLIB$$743c57e5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at org.yamj.core.database.service.MetadataStorageService$$EnhancerBySpringCGLIB$$eef2f53b.updateScannedPersonFilmography(<generated>)
	at org.yamj.core.service.metadata.MetadataScannerService.scanFilmography(MetadataScannerService.java:193)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by modmax** [comment]
Duplicate to #207
