### ISSUE TITLE
failed retrieving Allocine infos

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#212]
jetty loop thru error with a lot of movies with error on Allocine and TMDB 
[19:50:29] ERROR org.yamj.core.service.metadata.online.AllocineApiWrapper  - Failed retrieving Allocine infos for movie id 178185: ExceptionType=CONNECTION_ERROR, ResponseCode=0, URL=http://api.allocine.fr/rest/v3/movie?partner=100043982026&code=178185&profile=large&filter=movie&format=json&striptags=synopsis%2Csynopsisshort&sed=20150526&sig=%2BsTjn65R%2FoMuTsNPpCatT518UZk%3D
[19:50:29] ERROR org.yamj.core.service.metadata.online.AllocineScanner  - Can't find informations for movie 'Riddick'
[19:50:29] ERROR org.yamj.core.service.metadata.online.TheMovieDbApiWrapper  - Failed to get movie info using TMDb ID 87421: ExceptionType=CONNECTION_ERROR, ResponseCode=0, URL=http://api.themoviedb.org/3/movie/87421?api_key=5a1a77e2eba8984804586122754f969f&language=fr
[19:50:29] ERROR org.yamj.core.service.metadata.online.OnlineScannerService  - Failed scanning movie with tmdb alternate scanner
[19:50:29] WARN  org.yamj.core.service.metadata.online.OnlineScannerService  - Alternate scanning error
java.lang.NullPointerException
	at org.yamj.core.service.metadata.online.TheMovieDbScanner.scan(TheMovieDbScanner.java:144)
	at org.yamj.core.service.metadata.online.OnlineScannerService.scanMovie(OnlineScannerService.java:133)
	at org.yamj.core.service.metadata.MetadataScannerService.scanMovie(MetadataScannerService.java:72)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by modmax** [comment]
Is this just a temporary problem, or always?

**Comment by jluc2808** [comment]
i havn't made a global rescan since a while with the last version, so i think this issue could be a  temporary one, or append in coordination with several conditions which aren't obvious to describe now. 
too far from my mind. 
i will close this issue and will open a new one if the problem append another time.
