### ISSUE TITLE
Failed scanning person (ID '16854') data with scanner tmdb 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#214]
[00:39:28] ERROR org.yamj.core.service.metadata.online.OnlineScannerService  - Failed scanning person (ID '16854') data with scanner tmdb 
[00:39:28] WARN  org.yamj.core.service.metadata.online.OnlineScannerService  - Scanning error
java.lang.NullPointerException
	at com.omertron.themoviedbapi.methods.TmdbPeople.getPersonInfo(TmdbPeople.java:83)
	at com.omertron.themoviedbapi.TheMovieDbApi.getPersonInfo(TheMovieDbApi.java:1157)
	at org.yamj.core.service.metadata.online.TheMovieDbApiWrapper.getPersonInfo(TheMovieDbApiWrapper.java:140)
	at org.yamj.core.service.metadata.online.TheMovieDbScanner.scan(TheMovieDbScanner.java:280)
	at org.yamj.core.service.metadata.online.OnlineScannerService.scanPerson(OnlineScannerService.java:250)
	at org.yamj.core.service.metadata.MetadataScannerService.scanPerson(MetadataScannerService.java:158)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by modmax** [comment]
This is an issue within the TheMovieDB api, which is managed by Ometron.

So I will assign this bug to him in order to be solved within the API.

**Comment by jluc2808** [comment]
still some java error with tmdb scanner : 

[07:36:19] ERROR org.yamj.core.service.metadata.online.OnlineScannerService  - Failed scanning person (ID '2065') data with alternate scanner tmdb
[07:36:19] WARN  org.yamj.core.service.metadata.online.OnlineScannerService  - Alternate scanning error
java.lang.NullPointerException
	at com.omertron.themoviedbapi.methods.TmdbPeople.getPersonInfo(TmdbPeople.java:83)
	at com.omertron.themoviedbapi.TheMovieDbApi.getPersonInfo(TheMovieDbApi.java:1157)
	at org.yamj.core.service.metadata.online.TheMovieDbApiWrapper.getPersonInfo(TheMovieDbApiWrapper.java:140)
	at org.yamj.core.service.metadata.online.TheMovieDbScanner.scan(TheMovieDbScanner.java:280)
	at org.yamj.core.service.metadata.online.OnlineScannerService.scanPerson(OnlineScannerService.java:267)
	at org.yamj.core.service.metadata.MetadataScannerService.scanPerson(MetadataScannerService.java:158)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by modmax** [comment]
Following patch has to be done in TmdbPeope:

         // Switch combined credits for tv & movie.
         String atr = (String) parameters.get(Param.APPEND);
-        if (atr.contains("combined_credits")) {
+        if (atr != null && atr.contains("combined_credits")) {
             atr = atr.replace("combined_credits", "tv_credits,movie_credits");
             parameters.add(Param.APPEND, atr);
         }

**Comment by modmax** [comment]
Created ticket for TheMovieDbApi
https://github.com/Omertron/api-themoviedb/issues/26

More cannot be done at the moment, cause it's no YAMJ v3 error.
