### ISSUE TITLE
error with api/rescan/boxset/artwork/24

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#226]
i have tried to rescan the boxset   l'âge de glace

with the following error 
[22:49:04] ERROR org.hibernate.hql.internal.ast.ErrorCounter  - line 1:101: unexpected token: age
line 1:101: unexpected token: age
	at org.hibernate.hql.internal.antlr.HqlBaseParser.queryRule(HqlBaseParser.java:772)
	at org.hibernate.hql.internal.antlr.HqlBaseParser.selectStatement(HqlBaseParser.java:323)
	at org.hibernate.hql.internal.antlr.HqlBaseParser.statement(HqlBaseParser.java:186)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.parse(QueryTranslatorImpl.java:295)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:203)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:158)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:131)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:93)
	at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:167)
	at org.hibernate.internal.AbstractSessionImpl.getHQLQueryPlan(AbstractSessionImpl.java:301)
	at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:236)
	at org.hibernate.internal.SessionImpl.createQuery(SessionImpl.java:1836)
	at org.yamj.core.hibernate.HibernateDao.findByNamedParameters(HibernateDao.java:333)
	at org.yamj.core.hibernate.HibernateDao$$FastClassBySpringCGLIB$$d75d874c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649)
	at org.yamj.core.database.dao.StagingDao$$EnhancerBySpringCGLIB$$e8b9843b.findByNamedParameters(<generated>)
	at org.yamj.core.database.service.ArtworkLocatorService.getMatchingArtwork(ArtworkLocatorService.java:202)
	at org.yamj.core.database.service.ArtworkLocatorService$$FastClassBySpringCGLIB$$93093fb7.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at org.yamj.core.database.service.ArtworkLocatorService$$EnhancerBySpringCGLIB$$4da2d1dc.getMatchingArtwork(<generated>)
	at org.yamj.core.service.artwork.ArtworkScannerService.scanPosterLocal(ArtworkScannerService.java:177)
	at org.yamj.core.service.artwork.ArtworkScannerService.scanArtwork(ArtworkScannerService.java:126)
	at org.yamj.core.service.artwork.ArtworkScannerRunner.run(ArtworkScannerRunner.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[22:49:04] ERROR org.yamj.core.service.artwork.ArtworkScannerRunner  - Failed to process artwork
org.hibernate.QueryException: expecting ''', found '<EOF>' [select distinct f from org.yamj.core.database.model.StageFile f where lower(f.baseName) like 'set_l'age de glace_%'  and lower(f.baseName) not like '%fanart'  and lower(f.baseName) not like '%banner' and f.status != :deleted and f.fileType = :fileType ]
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:250)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:158)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:131)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:93)
	at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:167)
	at org.hibernate.internal.AbstractSessionImpl.getHQLQueryPlan(AbstractSessionImpl.java:301)
	at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:236)
	at org.hibernate.internal.SessionImpl.createQuery(SessionImpl.java:1836)
	at org.yamj.core.hibernate.HibernateDao.findByNamedParameters(HibernateDao.java:333)
	at org.yamj.core.hibernate.HibernateDao$$FastClassBySpringCGLIB$$d75d874c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649)
	at org.yamj.core.database.dao.StagingDao$$EnhancerBySpringCGLIB$$e8b9843b.findByNamedParameters(<generated>)
	at org.yamj.core.database.service.ArtworkLocatorService.getMatchingArtwork(ArtworkLocatorService.java:202)
	at org.yamj.core.database.service.ArtworkLocatorService$$FastClassBySpringCGLIB$$93093fb7.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at org.yamj.core.database.service.ArtworkLocatorService$$EnhancerBySpringCGLIB$$4da2d1dc.getMatchingArtwork(<generated>)
	at org.yamj.core.service.artwork.ArtworkScannerService.scanPosterLocal(ArtworkScannerService.java:177)
	at org.yamj.core.service.artwork.ArtworkScannerService.scanArtwork(ArtworkScannerService.java:126)
	at org.yamj.core.service.artwork.ArtworkScannerRunner.run(ArtworkScannerRunner.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by modmax** [comment]
Is a problem with an ' in the boxed set title which leads to a corrup sql syntax.
So I wil have to encode that for searching ...

**Comment by modmax** [comment]
I just updated the SQL queries for escaping sql search parameters.

Can you retry that what you have done for this issue nd post any error?

**Comment by jluc2808** [comment]
tested ok , now the rescan is performed , i will close this issue
