### ISSUE TITLE
timeout on metadate scanning

### ISSUE THREAD

**Issue by deblockt** [YAMJ/yamj-v3#242]
Hello,

I have try to scan a directory, on a debian server.
I have an error, while scanning metadata. This error happens always on the same serie.
I have a transaction timeout after series scanned.

After the log "Series 3-'The Mentalist', scanned OK", I have a pause 1 - 2 minutes, and after i have the timeout exception.

Have you an idea, why have i this exception?

```
Series 3-'The Mentalist', scanned OK
Failed storing series 3-'The Mentalist'
Storage error

org.hibernate.TransactionException: transaction timeout expired
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.determineRemainingTransactionTimeOutPeriod(JdbcCoordinatorImpl.java:271)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.setStatementTimeout(StatementPreparerImpl.java:208)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:187)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareStatement(StatementPreparerImpl.java:90)
        at org.hibernate.persister.entity.AbstractEntityPersister.getDatabaseSnapshot(AbstractEntityPersister.java:1526)
        at org.hibernate.engine.internal.StatefulPersistenceContext.getDatabaseSnapshot(StatefulPersistenceContext.java:317)
        at org.hibernate.engine.internal.ForeignKeys.isTransient(ForeignKeys.java:255)
        at org.hibernate.event.internal.AbstractSaveEventListener.getEntityState(AbstractSaveEventListener.java:521)
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:100)
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90)
        at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:684)
        at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:676)
        at org.hibernate.engine.spi.CascadingActions$5.cascade(CascadingActions.java:235)
        at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:350)
        at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:293)
        at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:161)
        at org.hibernate.engine.internal.Cascade.cascadeCollectionElements(Cascade.java:379)
        at org.hibernate.engine.internal.Cascade.cascadeCollection(Cascade.java:319)
        at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:296)
        at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:161)
        at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:118)
        at org.hibernate.event.internal.AbstractFlushingEventListener.cascadeOnFlush(AbstractFlushingEventListener.java:167)
        at org.hibernate.event.internal.AbstractFlushingEventListener.prepareEntityFlushes(AbstractFlushingEventListener.java:158)
        at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:91)
        at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:61)
        at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1227)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1293)
        at org.hibernate.internal.QueryImpl.list(QueryImpl.java:103)
        at org.hibernate.internal.AbstractQueryImpl.uniqueResult(AbstractQueryImpl.java:966)
        at org.yamj.core.database.dao.MetadataDao.getCastCrew(MetadataDao.java:143)
        at org.yamj.core.database.dao.MetadataDao$$FastClassBySpringCGLIB$$1858424.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
        at org.yamj.core.database.dao.MetadataDao$$EnhancerBySpringCGLIB$$eae5f897.getCastCrew(<generated>)
        at org.yamj.core.database.service.MetadataStorageService.updateCastCrew(MetadataStorageService.java:790)
        at org.yamj.core.database.service.MetadataStorageService.updateScannedMetaData(MetadataStorageService.java:408)
        at org.yamj.core.database.service.MetadataStorageService.updateScannedMetaData(MetadataStorageService.java:453)
        at org.yamj.core.database.service.MetadataStorageService$$FastClassBySpringCGLIB$$743c57e5.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
        at org.yamj.core.database.service.MetadataStorageService$$EnhancerBySpringCGLIB$$40ecfd38.updateScannedMetaData(<generated>)
        at org.yamj.core.service.metadata.MetadataScannerService.scanSeries(MetadataScannerService.java:132)
        at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:52)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)

```

**Comment by modmax** [comment]
The timeout occurs on low running transactions; so that those transactions will not block the entire process. In normal environments the timeout should not occure; mostly the will occur when the connection between the YAMJ3 application and the database (perhaps via internet) is slow.

I tweak the core application a little bit:
* Increased timeout for series from 2 minutes to 5 minutes
* Added caching mechanism for frequently requested database objects
* Reworked castcrew handling to run in-memory without database requests

**Comment by modmax** [comment]
Please try the latest snapshot from omertrons mediaplayersite and see, if that fixed your problems.
