### ISSUE TITLE
duplicate error entries for key 'UIX_ARTWORKLOCATED_NATURALID'

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#245]
[28.08.2015 20:01:12] WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - SQL Error: 1062, SQLState: 23000
[28.08.2015 20:01:12] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - Duplicate entry '564-tmdb-kjA2VkYx929rPKMPFQRb0lPqY3w' for key 'UIX_ARTWORKLOCATED_NATURALID'
[28.08.2015 20:01:12] WARN  org.yamj.core.database.service.UpgradeDatabaseService  - Failed upgrade 'patchArtworkLocated'
org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:59)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:207)
	at org.hibernate.engine.query.spi.NativeSQLQueryPlan.performExecuteUpdate(NativeSQLQueryPlan.java:194)
	at org.hibernate.internal.SessionImpl.executeNativeUpdate(SessionImpl.java:1315)
	at org.hibernate.internal.SQLQueryImpl.executeUpdate(SQLQueryImpl.java:373)
	at org.yamj.core.database.dao.UpgradeDatabaseDao.patchArtworkLocated(UpgradeDatabaseDao.java:661)
	at org.yamj.core.database.dao.UpgradeDatabaseDao$$FastClassBySpringCGLIB$$c48e56fa.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at org.yamj.core.database.dao.UpgradeDatabaseDao$$EnhancerBySpringCGLIB$$7d72c340.patchArtworkLocated(<generated>)
	at org.yamj.core.database.service.UpgradeDatabaseService.init(UpgradeDatabaseService.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:834)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:667)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:633)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:552)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:493)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:532)
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:344)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.yamj.jetty.Start.startUp(Start.java:155)
	at org.yamj.jetty.Start.main(Start.java:79)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '564-tmdb-kjA2VkYx929rPKMPFQRb0lPqY3w' for key 'UIX_ARTWORKLOCATED_NATURALID'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:400)
	at com.mysql.jdbc.Util.getInstance(Util.java:383)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3847)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3783)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1901)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2113)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2049)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2034)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:204)
	... 56 more

**Comment by modmax** [comment]
You have duplicate entries in your table "artwork_located", so that the unique key constraint cannot be applied.

The entry is:
'564-tmdb-kjA2VkYx929rPKMPFQRb0lPqY3w' 
where 
- artwork_id = 564
- source = tmdb
- hash_code = kjA2VkYx929rPKMPFQRb0lPqY3w

To select the columns run:

      select * from artwork_located where artwork_id=564 and source='tmdb' and hash_code='kjA2VkYx929rPKMPFQRb0lPqY3w'

This may have been occured due previous YAMJ3 versions, where no unique key constraint were used within that table.

Solution is to delete one of the duplicate columns via delete statement and apply the unique key constraint manually:

      ALTER TABLE artwork_located ADD UNIQUE INDEX UIX_ARTWORKLOCATED_NATURALID(artwork_id,source,hash_code)

**Comment by jluc2808** [comment]
couldn't delete the artwork_located entry because there a foreign key referenced as this is the same than the duplicated one i could suppress the artwork_id referenced so i'm could apply the ALTER instruction.

**Comment by modmax** [comment]
Following SQL's should solve the problems:

1.)
      delete from artwork_generated where located_id in ( 
      select id from artwork_located where artwork_id=564 and source='tmdb' and hash_code='kjA2VkYx929rPKMPFQRb0lPqY3w');

2.) 
      delete from artwork_located where artwork_id=564 and source='tmdb' and hash_code='kjA2VkYx929rPKMPFQRb0lPqY3w';

3.)
      ALTER TABLE artwork_located ADD UNIQUE INDEX UIX_ARTWORKLOCATED_NATURALID(artwork_id,source,hash_code)


if 3 doesn't work and another colulmn shich is not unique, is found, then steps 1 must be applied to the "another one failed" values and rerun the SQL statements.


An hardcore solutin is to drop all artworks.
      DELETE FROM artwork_generated;
      DELETE FROM artwork_located;
      UPDATE artwork SET status='NEW';

Then all arwork should be rescanned ...

**Comment by jluc2808** [comment]
Ok solved 

 

thanks

 

De : modmax [mailto:notifications@github.com] 
Envoyé : dimanche 30 août 2015 12:44
À : YAMJ/yamj-v3
Cc : jluc2808
Objet : Re: [yamj-v3] duplicate error entries for key 'UIX_ARTWORKLOCATED_NATURALID' (#245)

 

Following SQL's should solve the problems:

1.)
delete from artwork_generated where located_id in ( 
select id from artwork_located where artwork_id=564 and source='tmdb' and hash_code='kjA2VkYx929rPKMPFQRb0lPqY3w');

2.) 
delete from artwork_located where artwork_id=564 and source='tmdb' and hash_code='kjA2VkYx929rPKMPFQRb0lPqY3w';

3.)
ALTER TABLE artwork_located ADD UNIQUE INDEX UIX_ARTWORKLOCATED_NATURALID(artwork_id,source,hash_code)

if 3 doesn't work and another colulmn shich is not unique, is found, then steps 1 must be applied to the "another one failed" values and rerun the SQL statements.

An hardcore solutin is to drop all artworks.
DELETE FROM artwork_generated;
DELETE FROM artwork_located;
UPDATE artwork SET status='NEW';

Then all arwork should be rescanned ...

**Comment by jluc2808** [comment]
ok solved
