### ISSUE TITLE
storage error 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#248]
i get a lot of storage error  like : 
[29.08.2015 08:35:21] ERROR org.yamj.core.service.metadata.MetadataScannerService  - Storage error
java.lang.IllegalArgumentException: No enum constant org.yamj.core.database.model.type.ImageType.
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.yamj.core.hibernate.usertypes.EnumStringUserType.nullSafeGet(EnumStringUserType.java:198)
	at org.hibernate.type.CustomType.nullSafeGet(CustomType.java:110)
	at org.hibernate.type.AbstractType.hydrate(AbstractType.java:89)
	at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:2665)
	at org.hibernate.loader.plan.exec.process.internal.EntityReferenceInitializerImpl.loadFromResultSet(EntityReferenceInitializerImpl.java:308)
	at org.hibernate.loader.plan.exec.process.internal.EntityReferenceInitializerImpl.hydrateEntityState(EntityReferenceInitializerImpl.java:235)
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.readRow(AbstractRowReader.java:90)
	at org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl.extractResults(ResultSetProcessorImpl.java:112)
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:121)
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:85)
	at org.hibernate.loader.collection.plan.AbstractLoadPlanBasedCollectionInitializer.initialize(AbstractLoadPlanBasedCollectionInitializer.java:82)
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:683)
	at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:75)
	at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1918)
	at org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:545)
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:247)
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:541)
	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:132)
	at org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:163)
	at org.yamj.core.database.dao.CommonDao.markAsDeleted(CommonDao.java:520)
	at org.yamj.core.database.dao.CommonDao$$FastClassBySpringCGLIB$$3d2828.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at org.yamj.core.database.dao.CommonDao$$EnhancerBySpringCGLIB$$73b9ba11.markAsDeleted(<generated>)
	at org.yamj.core.database.service.MetadataStorageService.updateLocatedArtwork(MetadataStorageService.java:885)
	at org.yamj.core.database.service.MetadataStorageService.updateScannedPerson(MetadataStorageService.java:322)
	at org.yamj.core.database.service.MetadataStorageService$$FastClassBySpringCGLIB$$743c57e5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at org.yamj.core.database.service.MetadataStorageService$$EnhancerBySpringCGLIB$$fff5f72e.updateScannedPerson(<generated>)
	at org.yamj.core.service.metadata.MetadataScannerService.scanPerson(MetadataScannerService.java:159)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[29.08.2015 08:35:24] WARN  org.hibernate.engine.loading.internal.LoadContexts  - HHH000100: Fail-safe cleanup (collections) : org.hibernate.engine.loading.internal.CollectionLoadContext@73410c3f<rs=org.apache.commons.dbcp.DelegatingResultSet@4f0831f0>
[29.08.2015 08:35:24] WARN  org.hibernate.engine.loading.internal.CollectionLoadContext  - HHH000160: On CollectionLoadContext#cleanup, localLoadingCollectionKeys contained [1] entries
[29.08.2015 08:35:24] ERROR org.yamj.core.service.metadata.MetadataScannerService  - Failed storing person 7508-'Ivan Kaye'
[29.08.2015 08:35:24] ERROR org.yamj.core.service.metadata.MetadataScannerService  - Storage error
java.lang.IllegalArgumentException: No enum constant org.yamj.core.database.model.type.ImageType.
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.yamj.core.hibernate.usertypes.EnumStringUserType.nullSafeGet(EnumStringUserType.java:198)
	at org.hibernate.type.CustomType.nullSafeGet(CustomType.java:110)
	at org.hibernate.type.AbstractType.hydrate(AbstractType.java:89)
	at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:2665)
	at org.hibernate.loader.plan.exec.process.internal.EntityReferenceInitializerImpl.loadFromResultSet(EntityReferenceInitializerImpl.java:308)
	at org.hibernate.loader.plan.exec.process.internal.EntityReferenceInitializerImpl.hydrateEntityState(EntityReferenceInitializerImpl.java:235)
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.readRow(AbstractRowReader.java:90)
	at org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl.extractResults(ResultSetProcessorImpl.java:112)
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:121)
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:85)
	at org.hibernate.loader.collection.plan.AbstractLoadPlanBasedCollectionInitializer.initialize(AbstractLoadPlanBasedCollectionInitializer.java:82)
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:683)
	at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:75)
	at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1918)
	at org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:545)
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:247)
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:541)
	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:132)
	at org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:163)
	at org.yamj.core.database.dao.CommonDao.markAsDeleted(CommonDao.java:520)
	at org.yamj.core.database.dao.CommonDao$$FastClassBySpringCGLIB$$3d2828.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at org.yamj.core.database.dao.CommonDao$$EnhancerBySpringCGLIB$$73b9ba11.markAsDeleted(<generated>)
	at org.yamj.core.database.service.MetadataStorageService.updateLocatedArtwork(MetadataStorageService.java:885)
	at org.yamj.core.database.service.MetadataStorageService.updateScannedPerson(MetadataStorageService.java:322)
	at org.yamj.core.database.service.MetadataStorageService$$FastClassBySpringCGLIB$$743c57e5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at org.yamj.core.database.service.MetadataStorageService$$EnhancerBySpringCGLIB$$fff5f72e.updateScannedPerson(<generated>)
	at org.yamj.core.service.metadata.MetadataScannerService.scanPerson(MetadataScannerService.java:159)
	at org.yamj.core.service.metadata.MetadataScannerRunner.run(MetadataScannerRunner.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by modmax** [comment]
Th eproblem is that the patchArtworkLocated couldn't be done (due the unique key constraint violation from #245), so that the image type still is '', whoich cannot be mapped to a real type.
The patch should set '' to 'JPG' as default; but the patch was rolled backed ..

IUf #245 is solved then also this is solved.

**Comment by jluc2808** [comment]
tested ok
