### ISSUE TITLE
minor issue with java error 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#282]
could you trap this java error and display just the warn rather than the java error 

[31.03.2016 00:28:54] DEBUG org.yamj.core.service.artwork.ArtworkScannerService  - Scan online for photo: Artwork [ID=3162, type=PHOTO, person-id='Samantha Ellison']
[31.03.2016 00:28:54] DEBUG org.yamj.core.service.artwork.ArtworkScannerService  - Use allocine scanner for Person [ID=1926, identifier=Samantha Ellison, name=Samantha Ellison]
[31.03.2016 00:28:54] DEBUG org.yamj.core.service.artwork.ArtworkScannerService  - Use tmdb scanner for Person [ID=1926, identifier=Samantha Ellison, name=Samantha Ellison]
[31.03.2016 00:28:54] ERROR org.yamj.core.service.artwork.online.TheMovieDbArtworkScanner  - Failed retrieving PROFILE artworks for movie id 1559910: ExceptionType=HTTP_404_ERROR, ResponseCode=404, URL=http://api.themoviedb.org/3/person/1559910/images?api_key=5a1a77e2eba8984804586122754f969f
[31.03.2016 00:28:54] WARN  org.yamj.core.service.artwork.online.TheMovieDbArtworkScanner  - TheMovieDb error
com.omertron.themoviedbapi.MovieDbException: ExceptionType=HTTP_404_ERROR, ResponseCode=404, URL=http://api.themoviedb.org/3/person/1559910/images?api_key=5a1a77e2eba8984804586122754f969f
	at com.omertron.themoviedbapi.tools.HttpTools.validateResponse(HttpTools.java:155)
	at com.omertron.themoviedbapi.tools.HttpTools.getRequest(HttpTools.java:81)
	at com.omertron.themoviedbapi.methods.TmdbPeople.getPersonImages(TmdbPeople.java:221)
	at com.omertron.themoviedbapi.TheMovieDbApi.getPersonImages(TheMovieDbApi.java:1227)
	at org.yamj.core.service.artwork.online.TheMovieDbArtworkScanner.getArtworksFromTMDb(TheMovieDbArtworkScanner.java:336)
	at org.yamj.core.service.artwork.online.TheMovieDbArtworkScanner.getFilteredArtwork(TheMovieDbArtworkScanner.java:283)
	at org.yamj.core.service.artwork.online.TheMovieDbArtworkScanner.getFilteredArtwork(TheMovieDbArtworkScanner.java:241)
	at org.yamj.core.service.artwork.online.TheMovieDbArtworkScanner.getFilteredArtwork(TheMovieDbArtworkScanner.java:221)
	at org.yamj.core.service.artwork.online.TheMovieDbArtworkScanner.getPhotos(TheMovieDbArtworkScanner.java:137)
	at org.yamj.core.service.artwork.ArtworkScannerService.scanPhotoOnline(ArtworkScannerService.java:580)
	at org.yamj.core.service.artwork.ArtworkScannerService.processQueueElement(ArtworkScannerService.java:145)
	at org.yamj.core.scheduling.QueueProcessRunner.run(QueueProcessRunner.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by jluc2808** [comment]
tested ok
