### ISSUE TITLE
get a new error with filescanner 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#283]
i get a new error while using the filescanner , doesn't give any problem obviously after the filescanner run , so i report ab abstract of the log

[01.04.2016 06:32:18] INFO  org.yamj.filescanner.service.LibrarySendScheduler  - There are 1 libraries to process, there have been 0 consecutive failed attempts to send.
[01.04.2016 06:32:18] INFO  org.yamj.filescanner.service.LibrarySendScheduler  - There are 0 items currently queued to be sent to core.
[01.04.2016 06:32:18] INFO  org.yamj.filescanner.service.LibrarySendScheduler  -   T:\video\Film has 8 directories and the file scanner has not finished scanning.
[01.04.2016 06:32:18] INFO  org.yamj.filescanner.service.LibrarySendScheduler  -     T:\video\Film: NEW
[01.04.2016 06:32:18] INFO  org.yamj.filescanner.service.LibrarySendScheduler  -     Sending 'T:\video\Film' to core for processing.
[01.04.2016 06:32:18] INFO  org.yamj.filescanner.service.LibrarySendScheduler  - Sending #1: T:\video\Film
[01.04.2016 06:32:18] DEBUG org.yamj.filescanner.service.LibrarySendScheduler  - Successfully sent file to server.
[01.04.2016 06:32:18] ERROR org.springframework.aop.interceptor.SimpleAsyncUncaughtExceptionHandler  - Unexpected error occurred invoking async method 'public void org.yamj.filescanner.service.LibrarySendScheduler.sendLibraries()'.
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source)
	at org.yamj.filescanner.service.LibrarySendScheduler.sendLibraries(LibrarySendScheduler.java:104)
	at org.yamj.filescanner.service.LibrarySendScheduler$$FastClassBySpringCGLIB$$5d67f3dc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:108)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[01.04.2016 06:32:18] DEBUG org.yamj.filescanner.service.SendToCore  - Sending: T:\video\Film

**Comment by modmax** [comment]
This can happen if libraries are sent to core and another thread (due async handling) writes something which should be send into the actual send map, this means "concurrent modification".
This should be now problem at all; if the error occurs multiple times and video files are missing then
reopen this bug again.

Normally this should just be a warning; but this is not so easy to accomplish cause then another exception handler must be created (instead of the default one which comes out-of-the-box) just to handle this exception and leave other exceptions untouched to use the normal processing for them.

**Comment by jluc2808** [comment]
now just a warning - tested ok
