### ISSUE TITLE
error with mediaInfo while scanning movie La French

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#285]
if the error is 'normal' could you trap java error and just let warn message 

[02.04.2016 23:39:58] WARN  org.yamj.core.config.LocaleService  - No language code found for language 'frf'
[02.04.2016 23:39:58] ERROR org.yamj.core.service.mediainfo.MediaInfoService  - Failed MediaInfo scan for media file 603
org.hibernate.PropertyValueException: not-null property references a null or transient value : org.yamj.core.database.model.Subtitle.languageCode
	at org.hibernate.engine.internal.Nullability.checkNullability(Nullability.java:92)
	at org.hibernate.action.internal.AbstractEntityInsertAction.nullifyTransientReferencesIfNotAlready(AbstractEntityInsertAction.java:115)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:69)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:597)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:232)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:213)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:256)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:318)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:275)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:182)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:113)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:192)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:177)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:97)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:73)
	at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:651)
	at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:643)
	at org.hibernate.engine.spi.CascadingActions$5.cascade(CascadingActions.java:218)
	at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:391)
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:316)
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:155)
	at org.hibernate.engine.internal.Cascade.cascadeCollectionElements(Cascade.java:424)
	at org.hibernate.engine.internal.Cascade.cascadeCollection(Cascade.java:356)
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:319)
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:155)
	at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:104)
	at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:60)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.cascadeOnUpdate(DefaultSaveOrUpdateEventListener.java:357)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performUpdate(DefaultSaveOrUpdateEventListener.java:331)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsDetached(DefaultSaveOrUpdateEventListener.java:227)
	at org.hibernate.event.internal.DefaultUpdateEventListener.performSaveOrUpdate(DefaultUpdateEventListener.java:38)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:73)
	at org.hibernate.internal.SessionImpl.fireUpdate(SessionImpl.java:706)
	at org.hibernate.internal.SessionImpl.update(SessionImpl.java:698)
	at org.hibernate.internal.SessionImpl.update(SessionImpl.java:693)
	at org.yamj.core.hibernate.HibernateDao.updateEntity(HibernateDao.java:115)
	at org.yamj.core.hibernate.HibernateDao$$FastClassBySpringCGLIB$$d75d874c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:651)
	at org.yamj.core.database.dao.CommonDao$$EnhancerBySpringCGLIB$$3e9bcbec.updateEntity(<generated>)
	at org.yamj.core.database.service.MediaStorageService.updateMediaFile(MediaStorageService.java:70)
	at org.yamj.core.database.service.MediaStorageService$$FastClassBySpringCGLIB$$c0e0db22.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.yamj.core.database.service.MediaStorageService$$EnhancerBySpringCGLIB$$88c8c595.updateMediaFile(<generated>)
	at org.yamj.core.service.mediainfo.MediaInfoService.processQueueElement(MediaInfoService.java:190)
	at org.yamj.core.scheduling.QueueProcessRunner.run(QueueProcessRunner.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by modmax** [comment]
The error is not normal, but also not fixable ... reason is, that one audio codes contains a language name "frf", but it should be "fr" instead ...

So this issue will not be regarded, unless they are several errors of that kind, so that a fix is needed ... perhaps every french audio codes is representated as "frf" language by MediaInfo ... but I don't think so.
