### ISSUE TITLE
Java lang null pointer exception when lauching jetty instance

### ISSUE THREAD

**Issue by dav1170** [YAMJ/yamj-v3#316]
Hello,

When launching the jetty version one, I encounter many exception like this one:

```
Failed scan for artwork 1368
java.lang.NullPointerException
	at com.omertron.thetvdbapi.tools.DOMHelper.getEventDocFromUrl(DOMHelper.java:122)
	at com.omertron.thetvdbapi.tools.TvdbParser.getSeriesList(TvdbParser.java:256)
	at com.omertron.thetvdbapi.TheTVDBApi.searchSeries(TheTVDBApi.java:362)
	at org.yamj.plugin.thetvdb.TheTvDbApiWrapper.getSeriesId(TheTvDbApiWrapper.java:139)
	at org.yamj.plugin.thetvdb.AbstractTheTvDbScanner.getSeriesId(AbstractTheTvDbScanner.java:133)
	at org.yamj.plugin.thetvdb.TvDbSeriesArtworkScanner.getVideoImages(TvDbSeriesArtworkScanner.java:487)
	at org.yamj.core.service.artwork.ArtworkScannerService.scanVideoImageOnline(ArtworkScannerService.java:543)
	at org.yamj.core.service.artwork.ArtworkScannerService.processQueueElement(ArtworkScannerService.java:120)
	at org.yamj.core.scheduling.QueueProcessRunner.run(QueueProcessRunner.java:46)
	at org.yamj.core.scheduling.AbstractQueueScheduler.threadedProcessing(AbstractQueueScheduler.java:53)
	at org.yamj.core.scheduling.ArtworkScanScheduler.scanArtwork(ArtworkScanScheduler.java:101)
	at org.yamj.core.scheduling.ArtworkScanScheduler.run(ArtworkScanScheduler.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
here's the beginning of the startup:

```
null

[21.06.2017 19:31:14]INFO  org.yamj.common.model.YamjInfo  - Yet Another Movie Jukebox 3.0-SNAPSHOT

[21.06.2017 19:31:14]INFO  org.yamj.common.model.YamjInfo  
 ~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~
[21.06.2017 19:31:14]INFO  org.yamj.common.model.YamjInfo  - YAMJ3 Jetty
[21.06.2017 19:31:14]INFO  org.yamj.common.model.YamjInfo  - 
[21.06.2017 19:31:14]INFO  org.yamj.common.model.YamjInfo  -   Revision: 282ecdb (custom build)
[21.06.2017 19:31:14]INFO  org.yamj.common.model.YamjInfo  - Build Time: 2017-03-12 18:13:21 +0100
[21.06.2017 19:31:14]INFO  org.yamj.common.model.YamjInfo  -       Java: 1.8.0_121
[21.06.2017 19:31:14]INFO  org.yamj.common.model.YamjInfo  - 
[21.06.2017 19:31:14]INFO  org.yamj.jetty.Start  - YAMJ Home: '.'
[21.06.2017 19:31:14]INFO  org.yamj.jetty.Start  - YAMJ Port: 8888
[21.06.2017 19:31:14]INFO  org.yamj.jetty.Start  - YAMJ Shudown Timeout: 5000ms
[21.06.2017 19:31:14]INFO  org.yamj.jetty.Start  - YAMJ will stop at Shutdown
[21.06.2017 19:31:14]INFO  org.yamj.jetty.Start  - Using war file: lib/yamj3-core-3.0-SNAPSHOT.war
[21.06.2017 19:31:14]INFO  org.yamj.jetty.Start  - 
[21.06.2017 19:31:14]INFO  org.yamj.jetty.Start  - Starting server...
[21.06.2017 19:31:14]INFO  org.yamj.jetty.Start  - Resource base: file:XXXXXXXXXX
[21.06.2017 19:31:14]INFO  org.yamj.jetty.Start  - Skins directory: resources/skins/
[21.06.2017 19:31:14]INFO  org.eclipse.jetty.server.Server  - jetty-8.1.16.v20140903
[21.06.2017 19:31:14]INFO  org.eclipse.jetty.webapp.WebInfConfiguration  - Extract jar:file:XXXXXXXXXX/core/lib/yamj3-core-3.0-SNAPSHOT.war!/ to /tmp/jetty-0.0.0.0-8888-yamj3-core-3.0-SNAPSHOT.war-_yamj3-any-/webapp
[21.06.2017 19:31:17]INFO  /yamj3  - Set web app root system property: 'yamj3.root' = [/tmp/jetty-0.0.0.0-8888-yamj3-core-3.0-SNAPSHOT.war-_yamj3-any-/webapp]
[21.06.2017 19:31:17]INFO  /yamj3  - Initializing log4j from [/tmp/jetty-0.0.0.0-8888-yamj3-core-3.0-SNAPSHOT.war-_yamj3-any-/webapp/WEB-INF/log4j.properties]
[21.06.2017 19:31:17]INFO  /yamj3  - Initializing Spring FrameworkServlet 'yamj3'
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/tmp/jetty-0.0.0.0-8888-yamj3-core-3.0-SNAPSHOT.war-_yamj3-any-/webapp/WEB-INF/lib/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:XXXXXXXXXX/core/lib/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
[21.06.2017 19:31:20]INFO  org.yamj.common.tools.PropertyTools  - Loading properties file from class path resource [yamj3-core-static.properties]
[21.06.2017 19:31:20]INFO  org.yamj.common.tools.PropertyTools  - Loading properties file from file [/volume1/videos/jukebox/core/config/yamj3-core-static.properties]
[21.06.2017 19:31:20]INFO  org.yamj.common.tools.PropertyTools  - Loading properties file from file [/volume1/videos/jukebox/core/config/yamj3-core-static.user.properties]
Loaded 112 properties
Logging Provider: org.jboss.logging.Log4jLoggerProvider
YAMY locale: language=en, country=US
YAMY lookup languages:  1257
YAMY display languages: 2175
YAMY lookup countries:  2326
YAMY display countries: 4782
Using download limits: .*=2,.*imdb.*=2,.*google.*=5,.*yahoo.*=5,.*themoviedb.*=3,.*thetvdb.*=2,.*apple.*=1,.*trailersland.com=1,.fanart.tv=2
Initialize aspect ratio tools
Initialize attachment scanner service
MKV Toolnix Path : ./mkvToolnix
Couldn't find MKV toolnix executable tool 'mkvinfo'
Resource path set to 'resources'
Artwork storage path set to 'resources/artwork/'
MediaInfo storage path set to 'resources/mediainfo/'
Photo storage path set to 'resources/photo/'
Skins storage path set to 'resources/skins/'
Trailer storage path set to 'resources/trailer/'
PF4J version 0.13.1 in 'deployment' mode
Enabled plugins: []
Disabled plugins: []
Plugin 'yamj3-plugin-imdb' resolved
Plugin 'yamj3-plugin-ofdb' resolved
Plugin 'yamj3-plugin-allocine' resolved
Plugin 'yamj3-plugin-comingsoon' resolved
Plugin 'yamj3-plugin-thetvdb' resolved
Plugin 'yamj3-plugin-moviemeter' resolved
Plugin 'yamj3-plugin-fanarttv' resolved
Plugin 'yamj3-plugin-youtube' resolved
Plugin 'yamj3-plugin-themoviedb' resolved
Start plugin 'yamj3-plugin-imdb:3.0.3'
Start plugin 'yamj3-plugin-ofdb:3.0.2'
Start plugin 'yamj3-plugin-allocine:3.0.3'
Start plugin 'yamj3-plugin-comingsoon:3.0.3'
Start plugin 'yamj3-plugin-thetvdb:3.0.4'
Start plugin 'yamj3-plugin-moviemeter:3.0.2'
Start plugin 'yamj3-plugin-fanarttv:3.0.1'
Start plugin 'yamj3-plugin-youtube:3.0.1'
Start plugin 'yamj3-plugin-themoviedb:3.0.2'
Transliteration is not enabled
Initialize extras scanner
Initialize artwork profiles
Initialize MediaInfo service
Operating System Name   : Linux
Operating System Version: 3.10.102
Operating System Type   : amd64
Media Info Path         : XXXXXXXXXX
MediaInfo tool will be used to extract video data. But not RAR and ISO formats
IPv6 Address: XXXXXXXXXX
IPv4 Address: XXXXXXXXXX
8888
8888
Initialize plugin extensions
Initialize execution tasks
Registered task: artworksanity
Registered task: delete
Registered task: recheck
Registered task: trakttv
Registered task: stagingsanity
Use 2 threads for scheduled processing
[21.06.2017 19:32:02]INFO  org.eclipse.jetty.server.AbstractConnector  - Started SelectChannelConnector@0.0.0.0:8888
Found 4 metadata objects to process; scan with 1 threads
Scanning series data for '24' using allocine
IO download host: http://api.allocine.fr; rule: .*, maxRequests: 2
Found 60 artwork objects to scan; process with 1 threads
```

I don't know if this a plugin issue or this is due to an error during first initialization (I forgot to exclude a previous yamj2 jukebox folder).

Regards

**Comment by jluc2808** [comment]
it seems that all the java error are after an aborted scan of  artwork of a series scrapped from tvdb , does all the other error after the same series (1368) , do you scan from an NFO ? 
could you try with another site allocine , tmdb, imdb (remove tvdb from the list)

**Comment by dav1170** [comment]
All errors come from the same TV show.
I use nfo files but they have been generated from sickbeard.
With another plugin such as allocine, the errors does not happen.

**Comment by jluc2808** [comment]
could you give the exact tv show which open this error

**Comment by dav1170** [comment]
Hello Jluc2808,

the nfo file content or the tv show name?

regards

**Comment by jluc2808** [comment]
both are needed

**Comment by jluc2808** [comment]
please post the NFO to allow debugging

**Comment by jluc2808** [comment]
again dav1170 post the NFO

**Comment by dav1170** [comment]
Hello @jluc2808 

I'll do it when I'll be able to do it: for now, my filescanner always hang up and I'm looking for a way to restore it

**Comment by jluc2808** [comment]
doesn't matter of the result of the filescanner, i just want to take a look at the nfo contents you are using , i have some time for a few days but will be out next week

**Comment by dav1170** [comment]
Jluc,

I'm not able to reproduce it so I'm not able to find which was the nfo file which induce this exception.

regards

**Comment by jluc2808** [comment]
so i will close
