### ISSUE TITLE
org.yamj.filescanner.service.LibrarySendScheduler  - Execution error

### ISSUE THREAD

**Issue by dav1170** [YAMJ/yamj-v3#326]
Hello,

When running the filescanner I encounter many exception like this one:

> 27.07.2017 13:31:19]WARN  org.yamj.filescanner.service.LibrarySendScheduler  - Execution error
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to import scanned directory: /volume1/videos/films
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.yamj.filescanner.service.LibrarySendScheduler.sendLibraries(LibrarySendScheduler.java:105)
	at org.yamj.filescanner.service.LibrarySendScheduler$$FastClassBySpringCGLIB$$5d67f3dc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to import scanned directory: /volume1/videos/films
	at org.yamj.core.remote.service.FileImportServiceImpl.importScanned(FileImportServiceImpl.java:54)
	at sun.reflect.GeneratedMethodAccessor1373.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.remoting.support.RemoteInvocationTraceInterceptor.invoke(RemoteInvocationTraceInterceptor.java:78)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy93.importScanned(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor1672.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.remoting.support.RemoteInvocation.invoke(RemoteInvocation.java:212)
	at org.springframework.remoting.support.DefaultRemoteInvocationExecutor.invoke(DefaultRemoteInvocationExecutor.java:39)
	at org.springframework.remoting.support.RemoteInvocationBasedExporter.invoke(RemoteInvocationBasedExporter.java:78)
	at org.springframework.remoting.support.RemoteInvocationBasedExporter.invokeAndCreateResult(RemoteInvocationBasedExporter.java:114)
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.handleRequest(HttpInvokerServiceExporter.java:79)
	at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:869)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
	at org.springframework.remoting.support.RemoteInvocationUtils.fillInClientStackTraceIfPossible(RemoteInvocationUtils.java:45)
	at org.springframework.remoting.support.RemoteInvocationResult.recreate(RemoteInvocationResult.java:149)
	at org.springframework.remoting.support.RemoteInvocationBasedAccessor.recreateRemoteInvocationResult(RemoteInvocationBasedAccessor.java:85)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:150)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy13.importScanned(Unknown Source)
	at org.yamj.filescanner.service.SendToCore.call(SendToCore.java:72)
	at org.yamj.filescanner.service.SendToCore.call(SendToCore.java:39)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	... 4 more

begnning of the log file is:

> [27.07.2017 13:06:24] DEBUG org.yamj.common.tools.SystemTools  - System property 'yamj3.home' not found. Setting to '/volume1/videos/.jukebox/filescanner'
[27.07.2017 13:06:26] DEBUG org.yamj.common.tools.SystemTools  - IPv6 Address: fe80:0:0:0:211:32ff:fe62:43f3%eth0
[27.07.2017 13:06:26] DEBUG org.yamj.common.tools.SystemTools  - IPv4 Address: 192.168.2.6
[27.07.2017 13:06:26] INFO  org.yamj.common.model.YamjInfo  - Yet Another Movie Jukebox 3.0-SNAPSHOT
[27.07.2017 13:06:26] INFO  org.yamj.common.model.YamjInfo  - ~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~
[27.07.2017 13:06:26] INFO  org.yamj.common.model.YamjInfo  - YAMJ3 File Scanner
[27.07.2017 13:06:26] INFO  org.yamj.common.model.YamjInfo  - 
[27.07.2017 13:06:26] INFO  org.yamj.common.model.YamjInfo  -   Revision: 282ecdb (custom build)
[27.07.2017 13:06:26] INFO  org.yamj.common.model.YamjInfo  - Build Time: 2017-03-12 18:13:33 +0100
[27.07.2017 13:06:26] INFO  org.yamj.common.model.YamjInfo  -       Java: 1.8.0_121
[27.07.2017 13:06:26] INFO  org.yamj.common.model.YamjInfo  - 
[27.07.2017 13:06:33] INFO  org.yamj.common.tools.PropertyTools  - Loading properties file from class path resource [yamj3-filescanner.properties]
[27.07.2017 13:06:33] INFO  org.yamj.common.tools.PropertyTools  - Loading properties file from URL [file:/volume1/videos/.jukebox/filescanner/config/yamj3-filescanner.properties]
[27.07.2017 13:06:34] INFO  org.yamj.common.tools.PropertyTools  - Loading properties file from URL [file:/volume1/videos/.jukebox/filescanner/config/yamj3-filescanner.user.properties]
[27.07.2017 13:06:34] INFO  org.yamj.common.tools.PropertyTools  - Loaded 21 properties
[27.07.2017 13:06:36] DEBUG org.yamj.filescanner.ScannerManagementImpl  - Replaced pattern 'thumbs.db' with regex 'thumbs.db'
[27.07.2017 13:06:36] DEBUG org.yamj.filescanner.ScannerManagementImpl  - Directory exclusions: {temp=null, @eadir=null, .trash-1000=null, #recycle=null, jukebox=null, .mjbignore=null, sample=null, ._=null, conc
erts=null, .yamj3=null, tmp=null, .no_all.nmj=null, recycle.bin=null, nmj_database/=null, .jukebox=null}
[27.07.2017 13:06:36] DEBUG org.yamj.filescanner.ScannerManagementImpl  - File exclusions: [thumbs.db]
[27.07.2017 13:06:47] INFO  org.yamj.filescanner.service.LibrarySendScheduler  - There are 0 libraries to process, there have been 0 consecutive failed attempts to send.
[27.07.2017 13:06:47] INFO  org.yamj.filescanner.service.LibrarySendScheduler  - There are 0 items currently queued to be sent to core.
[27.07.2017 13:07:02] INFO  org.yamj.filescanner.service.LibrarySendScheduler  - There are 0 libraries to process, there have been 0 consecutive failed attempts to send.
[27.07.2017 13:07:02] INFO  org.yamj.filescanner.service.LibrarySendScheduler  - There are 0 items currently queued to be sent to core.
[27.07.2017 13:07:17] INFO  org.yamj.filescanner.service.LibrarySendScheduler  - There are 0 libraries to process, there have been 0 consecutive failed attempts to send.
[27.07.2017 13:07:17] INFO  org.yamj.filescanner.service.LibrarySendScheduler  - There are 0 items currently queued to be sent to core.
[27.07.2017 13:07:17] INFO  org.yamj.filescanner.ScannerManagementImpl  - Installation is less than 1 days old.
[27.07.2017 13:07:18] INFO  org.yamj.filescanner.service.SystemInfoCore  - Ping response: YAMJ3 Core is running
[27.07.2017 13:07:18] INFO  org.yamj.filescanner.service.SystemInfoCore  - Core server last checked at 2017-07-27 01:07:17 and connection status was connected
[27.07.2017 13:07:18] INFO  org.yamj.filescanner.ScannerManagementImpl  - Adding directory from command line: /volume1/videos
[27.07.2017 13:07:18] INFO  org.yamj.filescanner.ScannerManagementImpl  - Corrected path: /volume1/videos
[27.07.2017 13:07:18] INFO  org.yamj.filescanner.ScannerManagementImpl  - Found 1 libraries to process.
[27.07.2017 13:07:18] INFO  org.yamj.filescanner.ScannerManagementImpl  - Scanning library '/volume1/videos'...
[27.07.2017 13:07:18] INFO  org.yamj.filescanner.ScannerManagementImpl  - Scanning directory 'videos', detected type - STANDARD

execution has been launched with:
cd /volume1/videos/.jukebox/filescanner && ./my_filescanner.sh

my_filenscanner.sh content is:

> #!/bin/sh
# YAMJ3 File Scanner
# File Scanner client for YAMJ v3
# Version: 3.0-SNAPSHOT
# Git-SHA: 282ecdb89362c1938eff89e6b3f9f6fecb902607
clear
./filescanner.sh -d /volume1/videos

if the folder which has a problem is /volume1/videos/films, permissions on this folder are 755.

regards

**Comment by dav1170** [comment]
think this error is due to my core daemon which has hang up.
