### ISSUE TITLE
staging error with 177bd0c

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#332]
When I start a new scan I always get a staging error  :  with bluray, dvd or normal movie 
[10.03.2018 01:14:29] INFO  org.yamj.core.scheduling.TrailerScanScheduler  - Trailer scanning is disabled
[10.03.2018 01:14:33] DEBUG org.yamj.core.service.various.StagingService  - Updated directory: D:/temp/video/Film
[10.03.2018 01:14:33] DEBUG org.yamj.core.service.various.StagingService  - New directory: D:/temp/video/Film/Star Wars The Last Jedi (2017)
[10.03.2018 01:14:33] DEBUG org.yamj.core.service.various.StagingService  - New bluray file: D:\temp\video\Film\Star Wars The Last Jedi (2017)
[10.03.2018 01:14:33] DEBUG org.yamj.core.service.various.StagingService  - New directory: D:/temp/video/Film/Star Wars The Last Jedi (2017)/ANY!
[10.03.2018 01:14:33] DEBUG org.yamj.core.service.various.StagingService  - New directory: D:/temp/video/Film/Star Wars The Last Jedi (2017)/ANY!/DUPLICATE
[10.03.2018 01:14:33] DEBUG org.yamj.core.service.various.StagingService  - New directory: D:/temp/video/Film/Star Wars The Last Jedi (2017)/CERTIFICATE
[10.03.2018 01:14:33] DEBUG org.yamj.core.service.various.StagingService  - New directory: D:/temp/video/Film/Star Wars The Last Jedi (2017)/CERTIFICATE/BACKUP
[10.03.2018 01:14:34] INFO  org.yamj.core.service.mediaimport.MediaImportService  - Process new video 31-'Star Wars The Last Jedi (2017).bluray'
[10.03.2018 01:14:34] DEBUG org.yamj.core.service.mediaimport.MediaImportService  - Scanned filename 31-'Star Wars The Last Jedi (2017).bluray': title='Star Wars The Last Jedi', year=2017
[10.03.2018 01:14:34] DEBUG org.yamj.core.service.mediaimport.MediaImportService  - Store new media file: 'Star Wars The Last Jedi (2017).bluray'
[10.03.2018 01:14:34] DEBUG org.yamj.core.service.mediaimport.MediaImportService  - Store new movie: 'Star Wars The Last Jedi' - 2017
[10.03.2018 01:14:34] ERROR org.yamj.core.scheduling.ImportScheduler  - Failed to process video stage file 31
[10.03.2018 01:14:34] ERROR org.yamj.core.scheduling.ImportScheduler  - Staging Error
org.hibernate.QueryParameterException: could not locate named parameter [fileType]
                at org.hibernate.engine.query.spi.ParameterMetadata.getNamedParameterDescriptor(ParameterMetadata.java:131)
                at org.hibernate.engine.query.spi.ParameterMetadata.getNamedParameterExpectedType(ParameterMetadata.java:148)
                at org.hibernate.internal.AbstractQueryImpl.determineType(AbstractQueryImpl.java:517)
                at org.hibernate.internal.AbstractQueryImpl.setParameter(AbstractQueryImpl.java:487)
                at org.yamj.core.hibernate.HibernateDao.applyNamedParameterToQuery(HibernateDao.java:335)
                at org.yamj.core.hibernate.HibernateDao.applyNamedParameters(HibernateDao.java:322)
                at org.yamj.core.hibernate.HibernateDao.findByNamedParameters(HibernateDao.java:349)
                at org.yamj.core.database.dao.StagingDao.findStageFilesInSpecialFolder(StagingDao.java:393)
                at org.yamj.core.database.dao.StagingDao$$FastClassBySpringCGLIB$$b3402f6.invoke(<generated>)
                at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
                at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
                at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
                at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
                at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
                at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
                at org.yamj.core.database.dao.StagingDao$$EnhancerBySpringCGLIB$$48c636f5.findStageFilesInSpecialFolder(<generated>)
                at org.yamj.core.service.mediaimport.MediaImportService.attachNfoFilesToVideo(MediaImportService.java:480)
                at org.yamj.core.service.mediaimport.MediaImportService.processVideo(MediaImportService.java:126)
                at org.yamj.core.service.mediaimport.MediaImportService$$FastClassBySpringCGLIB$$495e56fa.invoke(<generated>)
                at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
                at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
                at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
                at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
                at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
                at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
                at org.yamj.core.service.mediaimport.MediaImportService$$EnhancerBySpringCGLIB$$d05d1398.processVideo(<generated>)
                at org.yamj.core.scheduling.ImportScheduler.processStageFiles(ImportScheduler.java:86)
                at org.yamj.core.scheduling.ImportScheduler.run(ImportScheduler.java:66)
                at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                at java.lang.reflect.Method.invoke(Unknown Source)
                at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
                at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
                at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
                at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
                at java.lang.Thread.run(Unknown Source)

**Comment by modmax** [comment]
Fixed with latest commit
